const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync(__dirname+'/src/TipoCambio.jsx','utf8');
const functions=src.slice(src.indexOf('export function fechaValida'),src.indexOf('export default function')).replaceAll('export ','');
const ctx={};vm.createContext(ctx);vm.runInContext(functions,ctx);
const tc={valor:17.4,fechaPublicacion:'2026-09-04',fechaCotizacion:'2026-09-07',confirmado:true};
assert.equal(ctx.validarCambio(tc,'2026-09-07'),'');
assert.ok(Math.abs(ctx.convertirUSD(1740,tc,'2026-09-07')-100)<1e-10);
assert.ok(ctx.validarCambio({...tc,fechaPublicacion:'2026-09-07'},'2026-09-07'));
assert.ok(ctx.validarCambio({...tc,fechaPublicacion:'2026-09-08'},'2026-09-07'));
assert.ok(ctx.validarCambio({...tc,valor:0},'2026-09-07'));
assert.ok(ctx.validarCambio({...tc,confirmado:false},'2026-09-07'));
assert.ok(ctx.validarCambio(tc,'2026-09-08'));
assert.ok(ctx.validarCambio({...tc,fechaPublicacion:'2026-02-30'},'2026-09-07'));
assert.ok(Number.isNaN(ctx.convertirUSD(1740,null,'2026-09-07')));
assert.ok(Math.abs(ctx.convertirUSD(1740,JSON.parse(JSON.stringify(tc)),'2026-09-07')-100)<1e-10);
const models=JSON.parse(fs.readFileSync(__dirname+'/src/modelos-usa-excel.json'));
assert.equal(models.length,73);assert.equal(new Set(models.map(m=>m.id)).size,73);
assert.equal(models.find(m=>m.id==='DEAN-1').totalMXN,127837.64);
assert.equal(models.filter(m=>m.perfil==='especial').length,44);
assert.equal(models.filter(m=>m.perfil==='normal').length,29);
const app=fs.readFileSync(__dirname+'/src/App.jsx','utf8');
assert.ok(!app.includes('${totalFinalAMostrar} MXN'));
assert.equal((app.match(/cambioDOF:market===/g)||[]).length,2);
assert.ok(app.includes('setCambioDOF(cot.config.cambioDOF || null)'));
console.log('18 verificaciones: conversión, fechas, persistencia y referencias Excel correctas.');
