import React,{useState} from 'react';
import {puertasReglas,gruposPrecios,numeroPrecio,tarifaGrupo} from './reglas-amacsa';
const money=n=>numeroPrecio(n)?new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n):'Consultar';
export function PuertasInteriores({q,db,onChange}){
 const p=puertasReglas(q,db),c=q.carroceria,list=p.puertas;
 const change=list=>onChange({...c,puertasIntList:list});
 const edit=(i,k,v)=>change(list.map((p,j)=>j===i?{...p,[k]:v}:p));
 return <div className="col-span-full border-t border-amber-200 pt-4 mt-4 space-y-3">
 <div className="flex justify-between gap-3"><b>Puertas interiores · Máximo {p.max}</b><button type="button" className="bg-amber-100 hover:bg-amber-200 text-amber-900 border border-amber-300 px-3 py-2 rounded-lg text-xs font-bold transition disabled:opacity-40" disabled={list.length>=p.max} onClick={()=>change([...list,{id:Date.now().toString(),tipo:'fija',distancia:0,desfase:0}])}>+ Agregar puerta</button></div>
 <label className="text-xs font-bold text-slate-500">Distribución <select className="p-2 border border-slate-300 rounded-md text-xs font-bold text-slate-800 normal-case bg-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 disabled:bg-slate-100 disabled:text-slate-400" value={c.modoPuertas||'automatico'} onChange={e=>onChange({...c,modoPuertas:e.target.value,puertasIntList:list})}><option value="automatico">Automática</option><option value="manual">Posiciones personalizadas</option></select></label>
 <p className="text-xs text-slate-600">Posiciones desde el frente del remolque, en pulgadas. Área útil: {(p.util/12).toFixed(2)} pies. Inicio después del monturero: {p.inicio} pulgadas.</p>
 {list.map((door,i)=><div key={door.id} className="flex flex-wrap gap-2 items-center bg-white border border-slate-200 rounded-xl p-3">
 <b>{i+1}.</b><select aria-label={`Tipo de puerta ${i+1}`} className="p-2 border border-slate-300 rounded-md text-xs font-bold text-slate-800 normal-case bg-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 disabled:bg-slate-100 disabled:text-slate-400" value={door.tipo} onChange={e=>edit(i,'tipo',e.target.value)}>{db.puertasInteriores.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select>
 <label className="text-xs font-bold text-slate-500">Posición (pulg.) <input className="p-2 border border-slate-300 rounded-md text-xs font-bold text-slate-800 normal-case bg-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 disabled:bg-slate-100 disabled:text-slate-400 w-24" aria-label={`Posición puerta ${i+1}`} type="number" step="0.5" disabled={c.modoPuertas!=='manual'} value={Number.isFinite(door.distancia)?door.distancia:''} onChange={e=>edit(i,'distancia',e.target.value)}/></label>
 {door.tipo==='diagonal'&&<label className="text-xs font-bold text-slate-500">Desplazamiento longitudinal (pulg.) <input className="p-2 border border-slate-300 rounded-md text-xs font-bold text-slate-800 normal-case bg-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 disabled:bg-slate-100 disabled:text-slate-400 w-24" type="number" min="0" step="0.5" value={door.desfase??0} onChange={e=>edit(i,'desfase',e.target.value)}/></label>}
 <span className="text-xs">Largo de puerta: {door.longitud} pulg.</span><button type="button" className="text-red-700 ml-auto" onClick={()=>change(list.filter((_,j)=>j!==i))}>Quitar</button></div>)}
 {!list.length&&<p>Sin puertas interiores.</p>}
 {p.errores.map(x=><p role="alert" className="text-red-700 font-bold text-sm" key={x}>{x}</p>)}
 {p.consulta&&<p className="text-amber-800 text-sm">{p.consulta}</p>}
 </div>;
}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function htmlLista(filas,db,tipo='todos') {
 const lista=filas.filter(z=>tipo==='todos'||z.tipo===tipo),grupos=gruposPrecios(lista);
 const head='<tr><th>Modelo</th><th>Ancho × largo</th><th>Capacidad</th><th>Equipo de lista</th><th>Precio MXN</th></tr>';
 const precioImpreso=z=>{if(z.tipo!=='ganadero_redondo')return z.precio;const porta=db.extras?.find(x=>x.id==='portaExtra')?.precio_ganadero_redondo;return numeroPrecio(z.precio)&&numeroPrecio(porta)?Number(z.precio)+Number(porta):null;};
 const body=lista.map(z=>`<tr><td>${escape(z.codigoLista||z.nombre)}</td><td>${escape(z.medidas)}</td><td>${escape(z.capacidad)}${z.capacidadId==='4t_6000'?' / 2 ejes 6,000 lb':z.capacidadId==='4t_5200'?' / 2 ejes 5,200 lb':''}</td><td>${escape(z.especificaciones)}</td><td>${money(precioImpreso(z))}</td></tr>`).join('');
 const tarifas=grupos.map(g=>{const t=tarifaGrupo(g,db.tarifasLargo,grupos),z=g.lista[0],precio=Number(t?.precio??g.propuesta);if(!Number.isFinite(precio)||precio<=0)return '';const texto=(z.especificaciones||z.nombre||'').toLowerCase();const detalle=z.tipo==='cama_baja'?[texto.includes('lámina')||texto.includes('lamina')?'Piso lámina':texto.includes('madera')?'Piso madera':'Piso no especificado',texto.includes('sin redila')?'Redila sin redila':texto.includes('cerrad')?'Redila cerrada':texto.includes('abiert')?'Redila abierta':'Redila no especificada'].join(' · '):'';return `<tr><td>${escape(z.tipo)}</td><td>${escape(z.capacidad)}</td><td>${escape(String(z.w).replace('.0',''))}&quot;</td><td>${money(precio)}</td><td>${escape(detalle?detalle+'; ':'')}${escape(g.lista.map(x=>x.codigoLista||x.nombre).join(', '))}</td></tr>`}).join('');
 const extra=[];for(const s of ['extras','gatos','llantas','jalones','puertasInteriores','rampas','pisos','redilas','suspension','puertasTraseras','montureros','pinturas','luces'])for(const x of db[s]||[]){const tipos=tipo==='todos'?['cama_baja','cama_alta','volteo','ganadero_redondo','ganadero_ganso_mex']: [tipo==='ganadero_ganso'?'ganadero_ganso_mex':tipo];for(const t of tipos){const field=s==='pisos'?'precioSqFt':'precio';const v=x[field+'_'+t];if(v!==undefined)extra.push(`<tr><td>${escape(t)}</td><td>${escape(x.nombre)}${field==='precioSqFt'?' (por pie²)':''}</td><td>${money(v)}</td></tr>`);if(['llantas','gatos'].includes(s)&&x['precioExtra_'+t]!==undefined)extra.push(`<tr><td>${escape(t)}</td><td>${escape(x.nombre)} - pieza adicional</td><td>${money(x['precioExtra_'+t])}</td></tr>`);}}
 return `<!doctype html><html lang="es"><meta charset="utf-8"><title>Lista de precios AMACSA</title><style>@page{size:letter;margin:14mm}body{font:10px Arial;color:#162c23}h1{color:#164d39}h2{margin-top:24px}table{width:100%;border-collapse:collapse}th{background:#164d39;color:white;text-align:left}td,th{padding:6px;border-bottom:1px solid #ccc}tr{break-inside:avoid}thead{display:table-header-group}button{padding:10px;margin-right:10px}@media print{.no-print{display:none}}.new{break-before:page}</style><div class="no-print"><button onclick="window.print()">Imprimir / Guardar PDF</button></div><h1>AMACSA · Lista de precios</h1><p>Emisión: ${new Date().toLocaleDateString('es-MX')} · MXN con IVA incluido. Precios de las listas proporcionadas; 2020 con 35 % ya aplicado una sola vez.</p><h2>Modelos base</h2><p>Esta tabla contiene únicamente modelos y precios base; no incluye tarifas por pie extra. Frente redondo: importes con un porta extra agregado. En 10 pies no incluye puerta central; en 12, 14 y 16 pies incluye una central corrediza y trasera corrediza.</p><table><thead>${head}</thead><tbody>${body}</tbody></table><h2 class="new">Tarifa por pie extra</h2><p>Cuadro independiente: Familia, capacidad, ancho, precio por pie extra y especificaciones. Se agrupan tarifas iguales y se omiten valores negativos. Para un largo que ya está en catálogo, use su precio exacto. Para otro largo: precio del modelo de catálogo inferior más cercano dentro del mismo grupo (incluye porta en frente redondo) + (largo solicitado - largo base) × cargo por pie. Mantenga ancho, capacidad y equipo; respete las medidas permitidas por diseño. Si es menor al largo base o falta tarifa: consultar.</p><table><thead><tr><th>Familia</th><th>Capacidad</th><th>Ancho</th><th>Precio por pie extra</th><th>Especificaciones</th></tr></thead><tbody>${tarifas}</tbody></table><h2 class="new">Cambios y accesorios</h2><p>Los cargos por cambio se suman una sola vez; no restar nuevamente el equipo incluido. “Consultar” no equivale a cero. Verificar compatibilidad y unidad de cobro. Frente redondo: esta tabla ya suma un porta extra al precio de las fotos; no lo sumes otra vez. Los otros modelos conservan el porta incluido según su configuración.</p><table><thead><tr><th>Tipo</th><th>Concepto</th><th>Cargo MXN</th></tr></thead><tbody>${extra.join('')}</tbody></table></html>`;
}
export function PanelTarifas({db,filas,onChange,canEdit}){
 const [tipo,setTipo]=useState('ganadero_redondo');
 const grupos=gruposPrecios(filas.filter(z=>tipo==='todos'||z.tipo===tipo));
 const update=(g,field,value)=>{const list=[...(db.tarifasLargo||[])],i=list.findIndex(x=>x.id===g.id),prev=i<0?(tarifaGrupo(g,list,grupos)||{id:g.id,nombre:g.nombre,precio:g.propuesta,validada:false}):list[i];const next={...prev,id:g.id,[field]:value};if(field!=='validada')next.validada=false;if(i<0)list.push(next);else list[i]=next;onChange(list);};
 const print=()=>{const w=window.open('','_blank');if(!w){alert('Permite abrir la ventana de la lista para imprimir.');return;}w.opener=null;w.document.write(htmlLista(filas,db,tipo));w.document.close();};
 return <section className="bg-white rounded-2xl border border-slate-200 p-5 my-5 space-y-4 text-slate-800"><h2 className="text-xl font-black text-green-900">Tarifas por largo y listas de precios</h2><div className="flex flex-wrap gap-3"><select className="p-2 border border-slate-300 rounded-md text-xs font-bold text-slate-800 normal-case bg-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 disabled:bg-slate-100 disabled:text-slate-400" value={tipo} onChange={e=>setTipo(e.target.value)}>{[['todos','Todos'],['ganadero_redondo','Ganadero redondo'],['ganadero_ganso','Ganadero con ganso'],['cama_baja','Cama baja'],['cama_alta','Cama alta'],['volteo','Volteo'],['caja_seca','Caja seca']].map(([id,n])=><option key={id} value={id}>{n}</option>)}</select><button type="button" onClick={print} className="bg-green-600 hover:bg-green-500 text-white rounded-lg px-4 py-2 text-sm font-bold transition shadow-sm">Abrir lista para imprimir / PDF</button></div><details className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-bold text-sm text-green-800">Editar tarifas por pie adicional</summary><p className="text-sm text-slate-600 mt-3">Precio por pie automático = diferencia de precios ÷ diferencia de largos, exclusivamente con el mismo ancho, capacidad y equipo. Se conserva el precio exacto de cada modelo de catálogo. Los valores propuestos se distinguen de las tarifas validadas.</p>
 <div className="max-h-[550px] overflow-auto space-y-3">{grupos.map(g=>{const t=tarifaGrupo(g,db.tarifasLargo,grupos);return <div className="border border-slate-200 rounded-xl bg-slate-50 p-4" key={g.id}><b>{g.nombre}</b><div className="flex flex-wrap items-end gap-3 mt-2"><p className="text-xs text-slate-600">Base automática: modelo inferior más cercano. Comparables: {g.lista.map(z=>z.l+' pies').join(', ')}.</p><label className="text-[10px] font-bold uppercase text-slate-500">MXN por pie<input aria-label={`Tarifa ${g.nombre}`} disabled={!canEdit} className="block mt-1 p-2 border border-slate-300 rounded-md text-xs font-bold text-slate-800 normal-case bg-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 disabled:bg-slate-100 disabled:text-slate-400 w-32" type="number" min="0" step="0.01" placeholder="Consultar" value={t?(t.precio??''):(g.propuesta??'')} onChange={e=>update(g,'precio',e.target.value===''?null:Number(e.target.value))}/></label><label className="text-sm"><input disabled={!canEdit||!(numeroPrecio(t?t.precio:g.propuesta))} type="checkbox" checked={!!t?.validada} onChange={e=>update(g,'validada',e.target.checked)}/> Tarifa validada</label></div><button disabled={!canEdit} type="button" className="mt-2 text-sm font-bold text-green-700 underline disabled:text-slate-400" onClick={()=>onChange((db.tarifasLargo||[]).filter(x=>x.id!==g.id&&(x.id!==g.idAnterior||grupos.filter(z=>z.idAnterior===g.idAnterior).length!==1)))}>Usar promedio automático</button>{g.duplicados&&<p className="text-red-700 text-sm">Variantes con el mismo largo: complete el equipo que las diferencia en Modelos de Línea.</p>}</div>})}</div></details></section>;
}
